language: clojure
lein: 2.9.1
before_install:
  - sudo apt-get -y install python3 python3-pip
  - sudo python3 -mpip install numpy
  - curl -O https://download.clojure.org/install/linux-install-1.10.1.507.sh
  - chmod +x linux-install-1.10.1.507.sh
  - sudo ./linux-install-1.10.1.507.sh
  - clojure -Sdescribe
addons:
  apt:
    update: true
install: clojure -Sdescribe
