#!/bin/bash

source activate pyclj

## This is absolutely necessary.
## https://github.com/conda/conda/issues/9500#issuecomment-565753807
export LD_LIBRARY_PATH="$(python3-config --prefix)/lib"


lein update-in :dependencies conj \[nrepl\ \"0.6.0\"\]\
     -- update-in :plugins conj \[cider/cider-nrepl\ \"0.22.4\"\]\
     -- repl :headless :host localhost
