#!/bin/bash

scripts/build-pyenv-poetry-docker

docker run --rm -it -u $(id -u):$(id -g) \
  -v /$HOME/.m2:/home/$USER/.m2 \
  -v $(pwd)/:/libpython-clj \
  --net=host -w /libpython-clj \
  docker-pyenv-poetry scripts/pyenv-poetry-repl
