#!/bin/bash

## This is incomplete, you still have to mess around with pythonpath and such.  The
## goal at this stage is to get this docker container to launch a repl that allows
## initialize! to work out of the box.

docker run --rm -it -u $(id -u):$(id -g) \
  -e LEIN_REPL_HOST="0.0.0.0" \
  -v /$HOME/.m2:/home/$USER/.m2 \
  -v /$HOME/.lein:/home/$USER/.lein \
  -v $(pwd)/:/libpython-clj \
  --net=host -w /libpython-clj \
  docker-conda /bin/bash

  # docker-conda lein update-in :dependencies conj \[nrepl\ \"0.6.0\"\]\
  # -- update-in :plugins conj \[cider/cider-nrepl\ \"0.22.4\"\]\
  # -- repl :headless :host localhost
